name: Vault JWT Authentication
on: workflow_dispatch
jobs:
  job-use-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Test
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github-access-aud" | base64 | base64
